# Generated by Django 3.1.7 on 2021-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
