# Generated by Django 3.1.7 on 2021-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_super_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
