# Generated by Django 3.1.7 on 2021-08-30 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_auto_20210818_1836'),
        ('main', '0004_auto_20210830_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='actions.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
