# Generated by Django 3.1.7 on 2021-04-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='promoted',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advanced'), (1, 'Middle'), (2, 'Begin')], default=2),
        ),
    ]
