# Generated by Django 3.1.7 on 2021-04-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_promoted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
