# Generated by Django 3.1.7 on 2021-07-29 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0003_auto_20210722_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('action', models.PositiveIntegerField(choices=[(1, 'User {subscriber} follow to {to_user}'),
                                                                (2, 'User {subscriber} follow to {to_user}'),
                                                                (3, 'User {user} liked {article}'),
                                                                (4, 'User {user} disliked {article}'),
                                                                (5, 'User {user} liked {comment}'),
                                                                (6, 'User {user} disliked {comment}')])),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
