# Generated by Django 3.1.7 on 2021-08-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20210729_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.TextField(),
        ),
    ]
